add init container
Signed-off-by: shiveshabhishek <shankeyshivesh@gmail.com>

diff --git a/chart1/templates/deployment.yaml b/chart1/templates/deployment.yaml
--- a/chart1/templates/deployment.yaml
+++ b/chart1/templates/deployment.yaml
@@ -21,6 +21,20 @@ spec:
         app.kubernetes.io/instance: {{ .Chart.Name }}
         namespace: {{ .Release.Namespace }}
     spec:
+      initContainers:
+      - name: check-configmap
+        image: busybox
+        command:
+        - sh
+        - -c
+        - |
+          if [ ! -f /usr/share/nginx/html/{{ .Chart.Name }}-index-html-configmap ]; then
+            echo "ConfigMap data not found. Exiting."
+            exit 1
+          fi
+        volumeMounts:
+        - name: config-volume
+          mountPath: /config
       containers:
         - name: {{ .Chart.Name }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
